### ISSUE TITLE
Fix unsafe redirects

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-admin#12]
In couple instances, we need to distinguish where the user is redirected based on his / her actions. We do so by a URL parameter "redirect" with redirect URL. However, this introduces an unvalidated redirect.

See this page for details: https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet

The issue is not super critical - admin users are system administrators, but we should still fix it.

**Comment by romanstrobl** [comment]
Fixed in https://github.com/wultra/powerauth-admin/pull/83/commits/d792a63eaa0aeb3a653c61d85c69226bdd8f8c6b
