### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by guptaarun111** [wultra/powerauth-admin#64]
I am getting below error when deployed power-auth admin.

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sun Sep 09 21:24:41 IST 2018
There was an unexpected error (type=Not Found, status=404).
No message available

Regards,
Arun
guptaarun11@gmail.com

**Comment by petrdvorak** [comment]
Hello Arun,

please do not use our public issue tracker as a support forum - visit our Gitter instead.

https://gitter.im/wultra/powerauth

Also, please provide us steps to reproduce when starting the discussion. How do you configure and run PA admin application? What version do you use? Etc.
